
export default function Head() {
    return (
      <>
          <title>Reserve at Fine Dine (Delhi) | OpenTable</title>
          <meta content="width=device-width,intial-scale=1" name="viewport"/>
          <meta name="description" content="Generated by create new app" />
          <link rel="icon" href="/favicon.ico" />
      </>
    );
  }
  