import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import NavBar from "./components/NavBar";
import AuthContext from "./context/AuthContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <main className="w-screen min-h-screen bg-gray-100">
         <AuthContext>
        <main className="max-w-screen-2xl m-auto bg-white">
        < NavBar/>
      {children}
      </main>
      </AuthContext>
      </main>
      </body>
    </html>
  );
}
